require ("user.plugins")
require ("user.keymaps")
require ("user.options")
require ("user.nvim-tree")
require ("user.colorscheme")
require ("user.telescope")
require ("user.harpoon")
require ("user.whichkey")
