local status_ok, treesitter = pcall(require, "nvim-treesitter.configs")
if not status_ok then
  vim.notify("Treesitter not loaded")
  return
end

local all_parsers = {
  "angular",
  "asm",
  "awk",
  "bash",
  "c",
  "c_sharp",
  "cmake",
  "comment",
  "commonlisp",
  "cpp",
  "css",
  "csv",
  "cue",
  "d",
  "dart",
  "diff",
  "dockerfile",
  "dot",
  "doxygen",
  "fish",
  "git_config",
  "git_rebase",
  "gitcommit",
  "gitignore",
  "go",
  "goctl",
  "gomod",
  "gosum",
  "gotmpl",
  "gowork",
  "graphql",
  "haskell",
  "haskell_persistent",
  "hcl",
  "helm",
  "html",
  "htmldjango",
  "http",
  "ini",
  "java",
  "javadoc",
  "javascript",
  "jinja",
  "jinja_inline",
  "jq",
  "json",
  "json5",
  "jsonnet",
  "julia",
  "kotlin",
  "lua",
  "luadoc",
  "luau",
  "make",
  "markdown",
  "markdown_inline",
  "mermaid",
  "nginx",
  "nickel",
  "objc",
  "passwd",
  "perl",
  "php",
  "php_only",
  "phpdoc",
  "promql",
  "proto",
  "python",
  "r",
  "readline",
  "regex",
  "rego",
  "rst",
  "ruby",
  "runescript",
  "rust",
  "scala",
  "scheme",
  "scss",
  "sql",
  "ssh_config",
  "terraform",
  "tmux",
  "toml",
  "tsv",
  "typescript",
  "typespec",
  "typoscript",
  "udev",
  "vim",
  "vimdoc",
  "vue",
  "xml",
  "yaml"
}

treesitter.setup({
  ensure_installed = all_parsers,
  sync_install = false,
  ignore_install = {
    "bicep",
    "hoon" -- https://github.com/urbit-pilled/tree-sitter-hoon/issues/5
  }, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { "bicep" }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = true, disable = { "yaml" } },
})
